"""empty message

Revision ID: 0e9541928b2a
Revises: f675b36c4f43
Create Date: 2024-12-12 19:20:18.983610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e9541928b2a'
down_revision = 'f675b36c4f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), nullable=True))
        batch_op.drop_column('isAnonymous')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAnonymous', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_hidden')
        batch_op.drop_column('is_anonymous')

    # ### end Alembic commands ###
