"""empty message

Revision ID: 263964163c0d
Revises: e2dd205f41d2
Create Date: 2024-12-14 22:22:27.338807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263964163c0d'
down_revision = 'e2dd205f41d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), nullable=True))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), nullable=True))

    with op.batch_alter_table('company_register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_register', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')

    # ### end Alembic commands ###
