"""empty message

Revision ID: 381e710fec17
Revises: 94c47a1cc28f
Create Date: 2025-01-11 01:33:11.030572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381e710fec17'
down_revision = '94c47a1cc28f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interval_start', sa.DateTime(), nullable=False),
    sa.Column('interval_end', sa.DateTime(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    # ### end Alembic commands ###
