"""empty message

Revision ID: 49354ce26234
Revises: fc882825a4b1
Create Date: 2024-12-13 18:45:11.772991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49354ce26234'
down_revision = 'fc882825a4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
