"""empty message

Revision ID: 5614f1dfaa23
Revises: 
Create Date: 2024-12-12 15:07:04.466409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5614f1dfaa23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company',
    sa.Column('id', sa.String(length=130), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=132), nullable=False),
    sa.Column('phone', sa.String(length=132), nullable=True),
    sa.Column('description', sa.String(length=132), nullable=False),
    sa.Column('website', sa.String(length=132), nullable=False),
    sa.Column('business_registration', sa.String(length=132), nullable=False),
    sa.Column('social_links', sa.String(length=132), nullable=False),
    sa.Column('logo', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.String(length=120), nullable=False),
    sa.Column('visits', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_registration'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('logo'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('social_links'),
    sa.UniqueConstraint('website')
    )
    op.create_table('company_register',
    sa.Column('id', sa.String(length=130), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=132), nullable=False),
    sa.Column('admin_email', sa.String(length=132), nullable=False),
    sa.Column('phone', sa.String(length=132), nullable=True),
    sa.Column('description', sa.String(length=132), nullable=False),
    sa.Column('website', sa.String(length=132), nullable=False),
    sa.Column('business_registration', sa.String(length=132), nullable=False),
    sa.Column('social_links', sa.String(length=132), nullable=False),
    sa.Column('logo', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_email'),
    sa.UniqueConstraint('business_registration'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('logo'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('social_links'),
    sa.UniqueConstraint('website')
    )
    op.create_table('branch',
    sa.Column('id', sa.String(length=130), nullable=False),
    sa.Column('company_id', sa.String(length=130), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('visits', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=130), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.String(length=130), nullable=True),
    sa.Column('branch_id', sa.String(length=130), nullable=True),
    sa.Column('created_at', sa.String(length=120), nullable=False),
    sa.Column('avatar', sa.String(length=120), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('review',
    sa.Column('id', sa.String(length=130), nullable=False),
    sa.Column('user_id', sa.String(length=130), nullable=True),
    sa.Column('branch_id', sa.String(length=130), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('staff_satisfaction', sa.Float(), nullable=False),
    sa.Column('speed_satisfaction', sa.Float(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(length=120), nullable=False),
    sa.Column('tags', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flagged',
    sa.Column('id', sa.String(length=130), nullable=False),
    sa.Column('review_id', sa.String(length=130), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.String(length=130), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.String(length=130), nullable=False),
    sa.Column('review_id', sa.String(length=130), nullable=True),
    sa.Column('user_id', sa.String(length=130), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response',
    sa.Column('id', sa.String(length=130), nullable=False),
    sa.Column('review_id', sa.String(length=130), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.String(length=130), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    op.drop_table('likes')
    op.drop_table('flagged')
    op.drop_table('review')
    op.drop_table('users')
    op.drop_table('branch')
    op.drop_table('company_register')
    op.drop_table('company')
    op.drop_table('role')
    op.drop_table('category')
    # ### end Alembic commands ###
