"""empty message

Revision ID: 66cdf035cd31
Revises: 88fc0a38feaa
Create Date: 2025-01-10 22:54:21.726701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cdf035cd31'
down_revision = '88fc0a38feaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_register', schema=None) as batch_op:
        batch_op.drop_index('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_register', schema=None) as batch_op:
        batch_op.create_index('phone', ['phone'], unique=True)

    # ### end Alembic commands ###
