"""empty message

Revision ID: 6ddf0b94a15b
Revises: c7118f3579d2
Create Date: 2025-01-10 20:52:24.174944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ddf0b94a15b'
down_revision = 'c7118f3579d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('business_registration',
               existing_type=mysql.VARCHAR(length=132),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('business_registration',
               existing_type=mysql.VARCHAR(length=132),
               nullable=False)

    # ### end Alembic commands ###
