"""empty message

Revision ID: 72963178597d
Revises: 
Create Date: 2025-01-10 22:51:21.928583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72963178597d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_register', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=120),
               nullable=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_experience', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('date_of_experience')

    with op.batch_alter_table('company_register', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.String(length=120),
               type_=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
