"""empty message

Revision ID: 88fc0a38feaa
Revises: 9ea325119c5e
Create Date: 2025-01-10 22:53:29.693178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fc0a38feaa'
down_revision = '9ea325119c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_register', schema=None) as batch_op:
        batch_op.drop_index('logo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_register', schema=None) as batch_op:
        batch_op.create_index('logo', ['logo'], unique=True)

    # ### end Alembic commands ###
