"""empty message

Revision ID: 8fde021f4343
Revises: 263964163c0d
Create Date: 2025-01-09 13:29:29.708346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fde021f4343'
down_revision = '263964163c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_quality', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('delivery_speed', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('ease_of_use', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('customer_service', sa.Float(), nullable=False))
        batch_op.drop_column('speed_satisfaction')
        batch_op.drop_column('reliability')
        batch_op.drop_column('staff_satisfaction')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_satisfaction', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('reliability', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('speed_satisfaction', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('customer_service')
        batch_op.drop_column('ease_of_use')
        batch_op.drop_column('delivery_speed')
        batch_op.drop_column('price')
        batch_op.drop_column('product_quality')

    # ### end Alembic commands ###
