"""empty message

Revision ID: 94c47a1cc28f
Revises: c5ddf67aaedc
Create Date: 2025-01-11 01:27:30.568453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c47a1cc28f'
down_revision = 'c5ddf67aaedc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.String(length=130), nullable=False),
    sa.Column('otp', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otp')
    # ### end Alembic commands ###
