"""empty message

Revision ID: 962a8da2eba2
Revises: c97ee8cefd16
Create Date: 2025-01-09 20:07:37.965860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962a8da2eba2'
down_revision = 'c97ee8cefd16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_users',
    sa.Column('id', sa.String(length=130), nullable=False),
    sa.Column('company_id', sa.String(length=130), nullable=True),
    sa.Column('user_id', sa.String(length=130), nullable=True),
    sa.Column('guest_id', sa.String(length=130), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_users')
    # ### end Alembic commands ###
