"""empty message

Revision ID: 9bba83d218d3
Revises: db3753f75640
Create Date: 2025-01-10 00:13:22.309353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bba83d218d3'
down_revision = 'db3753f75640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index('idx_company_id_hidden')
        batch_op.drop_index('idx_company_visits')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index('idx_company_visits', ['visits'], unique=False)
        batch_op.create_index('idx_company_id_hidden', ['id', 'is_hidden'], unique=False)

    # ### end Alembic commands ###
