"""empty message

Revision ID: 9ea325119c5e
Revises: 72963178597d
Create Date: 2025-01-10 22:52:33.433699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea325119c5e'
down_revision = '72963178597d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_register', schema=None) as batch_op:
        batch_op.drop_index('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_register', schema=None) as batch_op:
        batch_op.create_index('description', ['description'], unique=True)

    # ### end Alembic commands ###
