"""empty message

Revision ID: ba5d411ae011
Revises: 5614f1dfaa23
Create Date: 2024-12-12 18:09:45.242759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5d411ae011'
down_revision = '5614f1dfaa23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAnonymous', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('isAnonymous')

    # ### end Alembic commands ###
