"""empty message

Revision ID: c5ddf67aaedc
Revises: 66cdf035cd31
Create Date: 2025-01-10 23:07:44.647192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ddf67aaedc'
down_revision = '66cdf035cd31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index('description')
        batch_op.drop_index('email')
        batch_op.drop_index('logo')
        batch_op.drop_index('phone')
        batch_op.drop_index('social_links')
        batch_op.drop_index('website')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index('website', ['website'], unique=True)
        batch_op.create_index('social_links', ['social_links'], unique=True)
        batch_op.create_index('phone', ['phone'], unique=True)
        batch_op.create_index('logo', ['logo'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.create_index('description', ['description'], unique=True)

    # ### end Alembic commands ###
