"""empty message

Revision ID: c7118f3579d2
Revises: 9bba83d218d3
Create Date: 2025-01-10 17:55:30.055997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7118f3579d2'
down_revision = '9bba83d218d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_register', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
