"""empty message

Revision ID: ce588424a384
Revises: 8fde021f4343
Create Date: 2025-01-09 14:29:45.925121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce588424a384'
down_revision = '8fde021f4343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.String(length=130), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_register', schema=None) as batch_op:
        batch_op.alter_column('business_registration',
               existing_type=mysql.VARCHAR(length=132),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_register', schema=None) as batch_op:
        batch_op.alter_column('business_registration',
               existing_type=mysql.VARCHAR(length=132),
               nullable=False)

    op.drop_table('guest')
    # ### end Alembic commands ###
