"""empty message

Revision ID: db3753f75640
Revises: 962a8da2eba2
Create Date: 2025-01-09 23:43:53.897895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3753f75640'
down_revision = '962a8da2eba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index('idx_company_id_hidden', ['id', 'is_hidden'], unique=False)
        batch_op.create_index('idx_company_visits', ['visits'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index('idx_company_visits')
        batch_op.drop_index('idx_company_id_hidden')

    # ### end Alembic commands ###
