"""empty message

Revision ID: f675b36c4f43
Revises: ba5d411ae011
Create Date: 2024-12-12 18:22:31.439551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f675b36c4f43'
down_revision = 'ba5d411ae011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flagged', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged_at', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flagged', schema=None) as batch_op:
        batch_op.drop_column('flagged_at')

    # ### end Alembic commands ###
